import Header from './Header';
import Footer from './Footer';
import Head from 'next/head';

const Layout = ( {children} ) => {
  return (
    <main className='bg-dark d-flex flex-column min-vh-100'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='text-center'>
        {children}
      </div>
      <Footer />
    </main>
  );
};

export default Layout;
